mysite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from theme.views import change_theme
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('switch-theme', change_theme, name='change-theme'),
    path("__reload__/", include("django_browser_reload.urls")),
    # path('', include('tools.urls')),
    # path('account/', include('account.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
]

urlpatterns += i18n_patterns (
    path('account/', include('account.urls')),
    path('', include('tools.urls')),
    path('admin/', admin.site.urls),
)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]

if settings.DEBUG is True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tools/urls.py
from django.urls import path
from .views import (
        display_tool,
        tool_detail,
        add_Tool,
        update_Tool,
        delete_Tool,
        search_tool,
        
        smtp_template,
        sender_template,
        shell_template,
        
        #django_lang
        # switch_language,

        
        # -- Coinbase_Payment -- 
        Coinbase_Payment,
        coinbase_postback,
        
        purchaesd_emails,
    )

urlpatterns = [
    path('', display_tool, name="display_tool"),
    path('tool/<slug:slug>/', tool_detail, name="tool_detail"),
    path('add-tool/', add_Tool, name="add_tool"),
    path('update-Tool/<str:pk>', update_Tool, name="update_tool"),
    path('delete-Tool/<str:pk>', delete_Tool, name="delete_tool"),
    
    
    # display tool
    path('smtp', smtp_template ,name='smtp_template'), 
    path('sender', sender_template ,name='sender_template'),
    path('shell', shell_template ,name='shell_template'),
    
    
    path('search/', search_tool, name='search_tool'),
    
    # path('switch-language/', switch_language, name='switch_language'),
    
    
    path('coinbase_payment/<int:id>/', Coinbase_Payment, name="Coinbase_Payment"),
    path('coinbase_postback/', coinbase_postback, name="coinbase_postback"),
    
    path('purchaesd_emails/', purchaesd_emails, name='purchaesd_emails'),
    
    
]

tools/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from datetime import timedelta
from django.utils.text import slugify
# Create your models here.

class type_tool(models.Model):
    name = models.CharField(max_length=250)
    
    def __str__(self):
        return self.name

class Tool(models.Model):
    tool_name = models.CharField(max_length=350)
    type_of_tool = models.ForeignKey(type_tool, on_delete=models.CASCADE)
    slug = models.SlugField(unique=True, blank=True)
    image = models.ImageField(upload_to='tools/images')
    rating = models.FloatField(default=1)
    username = models.ForeignKey(User, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    upload_tool = models.FileField(upload_to='tools/uploads')
    quantity = models.PositiveIntegerField()
    is_visible = models.BooleanField(default=True)
    tool_sold = models.PositiveIntegerField(default=0)
    coinbase_payment_id = models.CharField(max_length=100)
    token = models.CharField(max_length=250)
    token_expiration = models.DateTimeField(blank=True, null=True) #يحدد تاريخ انتهاء سريان التوكن.
    # purchased_by = models.ManyToManyField(User, related_name='purchased_tools')
    
    # def is_purchased_by(self, user):
    #     return self.purchased_by.filter(id=user.id).exists()
    
    
    def __str__(self) -> str:
        return self.tool_name
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.tool_name)
        super().save(*args, **kwargs)
    
    
    class Meta:
        ordering = ['-created_at']
    
    def activate_token(self):
        # تحديد مدة السريان بناءً على المبلغ المدفوع (مثلاً بالأشهر)
        if self.price <= 100:
            duration = timedelta(days=30) # تشغيل التوكن لمدة شهر
        else:
            duration = timedelta(days=365)  # تشغيل التوكن لمدة سنة
        
        
        # حساب تاريخ انتهاء السريان بناءً على تاريخ اليوم ومدة السريان
        expiration_date = timezone.now() + duration
        
        # حفظ تاريخ انتهاء السريان في حقل التوكن
        self.token_expiration = expiration_date
        self.save()
        
    
    # تقليل الكمية عندما المستخدمون يقومون بشراء الاداة
    def reduce_quantity(self):
        if self.quantity > 0:
            self.quantity -= 1
            if self.quantity == 0:
                self.is_visible = False
            self.save()

    
    def purchase_tool(self, payment_id):
        self.tool_sold += 1 #  زيادة عدد المبيعات للاداة
        self.coinbase_payment_id = payment_id # تخزن معرّف عملية الدفع المرتبطة بالأداة
        self.activate_token() #تقوم بتشغيل التوكن للأداة باستخدام دالة عند عملة الشراء
        self.reduce_quantity() # تقلل الكمية المتاحة للأداة بواحد
        self.save() #يتم حفظ التغييرات المحدثة في قاعدة البيانات
        
        


class CoinBaseProcess(models.Model):
    code =  models.CharField(max_length=30, primary_key=True)
    email = models.EmailField(max_length=254)
    amount = models.FloatField()
    date = models.DateTimeField(auto_now_add=True)
    tool_name = models.CharField(max_length=250)
    product_id = models.IntegerField()
    
    class Meta:
        db_table = 'Coinbase Payment'
        
    def __str__(self):
        return f'{self.email} has bought {self.product_name} with {self.amount} $'

theme/views.py
from django.shortcuts import redirect
from django.http import HttpResponseRedirect


def change_theme(request, **kwargs):
    if 'is_dark_theme' in request.session:
        request.session['is_dark_theme'] = not request.session.get('is_dark_theme')
    else:
        request.session['is_dark_theme'] = True
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

tools/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.utils.translation import gettext_lazy as _
from django.utils.translation import get_language, activate, gettext_lazy
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect,HttpResponse
from .models import Tool, type_tool, CoinBaseProcess
from account.models import Profile
from django.contrib import messages
from .form import ToolForm
import json
import requests
# Create your views here.


def search_tool(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''
    tools = Tool.objects.filter(tool_name__icontains=q)
    
    context={
        'tools': tools,
        'q':q,
    }
    return render(request, 'tools/search_results.html', context)


def display_tool(request):
    trans = translate(language='ar')
    tools = Tool.objects.all()
    context={'tools':tools}
    return render(request, 'tools/products.html', context)

def translate(language):
    cur_language = get_language()
    try:
        activate(language)
        text = _('hello')
    finally:
        activate(cur_language)
    return text

# def switch_language(request):
#     if request.method == 'POST':
#         language = request.POST.get('language',  'en') # 'en' is the default language (English)
#         if language in ['en', 'tr', 'ru']: # Ensure the language is one of the available languages
#             print(f"Switching language to {language}")
#             request.session['django_language'] = language
    
#     referring_page = request.META.get('HTTP_REFERER', '/') # Get the referring page or use the homepage as a fallback
#     print(f"Redirecting to {referring_page}")
#     return redirect(referring_page)

@staff_member_required
@login_required()
def add_Tool(request):
    type_tools = type_tool.objects.all()
    if request.method == 'POST':
        form = ToolForm(request.POST, request.FILES)
        if form.is_valid():
            tool = form.save(commit=False)
            tool.username = request.user
            tool.save()
            messages.success(request, _('Tool added successfully'))
            # #حدد نوع الأداة
            # tool_type = form.cleaned_data.get('type_of_tool')
            
            # # أعد توجيه المستخدم إلى القالب المناسب بناءً على نوع الأداة
            # if tool_type == 'smtp':
            #     return redirect('smtp_template')
            # elif tool_type == 'sender':
            #     return redirect('sender_template')
            # elif tool_type == 'shell':
            #     return redirect('shell_template')
            return redirect('display_tool')
            
        else:
            print(form.errors)
            messages.error(request, _('try again'))
            return redirect('add_tool')
    else:
        form = ToolForm()
    
    context={
        'form':form,
        'type_tools':type_tools,
    }
    return render(request, 'tools/tool_form.html', context)


def smtp_template(request):
    tools = Tool.objects.filter(type_of_tool__name='smtp')
    context={'tools':tools}
    return render(request, 'tools/temp_tool/smtp_template.html', context)

def sender_template(request):
    tools = Tool.objects.filter(type_of_tool__name='sender')
    context={'tools':tools}
    return render(request, 'tools/temp_tool/sender_template.html', context)

def shell_template(request):
    tools = Tool.objects.filter(type_of_tool__name='shell')
    context={'tools':tools}
    return render(request, 'tools/temp_tool/shell_template.html', context)


def tool_detail(request, slug):
    tool = get_object_or_404(Tool, slug=slug)
    context={'tool':tool}
    return render(request, 'tools/product.html', context)


@login_required(login_url='login_view')
@staff_member_required
def update_Tool(request, pk):
    tool = get_object_or_404(Tool ,id=pk)
    if request.method == 'POST':
        form = ToolForm(request.POST, request.FILES, instance=tool)
        if form.is_valid():
            form.save()
            messages.success(request, _('Tool updated successfully'))
            return redirect('display_tool')
        
        else:
            messages.error(request, _('try again'))
            return redirect('update_tool')
    else:
        
        form = ToolForm(instance=tool)
    context={'form':form}
    return render(request, 'tools/tool_form.html', context)

@staff_member_required
def delete_Tool(request, pk):
    tool = get_object_or_404(Tool, pk=pk)
    if request.method == 'POST':
        tool.delete()
        messages.success(request, _('Tool deleted successfully'))
        return redirect('display_tool')
    
    context={'tool':tool}
    return  render(request, 'tools/delete-product.html', context)


@require_POST
def Coinbase_Payment(request, *args, **kwargs):
    post_data = request.POST 
    data = dict() #لتخزين البيانات التي سيتم إرسالها، مثل المعلومات حول المنتج والمبلغ 
    
    headers = dict() #لتخزين المعلومات المتعلقة بالاتصال نفسه
    id = post_data['id'] # id of the tool to  be purchased
    
    product_info = Tool.objects.filter(id=id)
    product_name = product_info[0].tool_name
    
    if product_info:
        product_info = product_info[0]
        price = product_info.price
        user = request.user.email
        api_key = 'f0cecb79-a4b2-436f-a131-b215cbe6fd44'
        url = 'https://api.commerce.coinbase.com/charges'
        
        data['meta_data'] = {
            'id': id,
            'customer': user
        }
        data['name'] = f'Buy {product_name} With {price}'
        data['description'] = 'Sellix Shop'
        data['pricing_type'] = 'fixed_price'
        data['local_price'] = {
            'amount': str(price),
            'currency': 'USD'
        }
        data['cancel_url'] = 'https://localhost.com'
        data['redirect_url'] = 'https://localhost.com'
        headers = {
            'content-type': 'application/json',
            'X-CC-Api-Key': api_key,
            'X-CC-Version': '2018-03-22'
        }
        
        response = requests.post(url=url, data=json.dumps(data), headers=headers)
        confirmed_data = json.loads(response.text)
        try:
            payment_url = confirmed_data['data']['hosted_url']
        except KeyError:
            payment_url = None # or set a default value
        
        return HttpResponseRedirect(payment_url)
    else:
        return redirect('payment')

# لماال api الخاص ب coinbase يبعتلك رد بان العمليه نجحت ول اترفضت والبيانات كمان
def coinbase_postback(request):
    if request.method == 'POST':
        values = json.loads(request.body.decode('utf-8'))
        status = False
        support_email = values['event']['data']['support_email']
        code = values['event']['data']['code']
        product_id = values['event']['data']['metadata']['id']
        value = values['event']['data']['pricing']['local']['amount']
        payment_currency = values['event']['data']['pricing']['local']['currency']
        customer = values['event']['data']['metadata']['customer']
        product_name = values['event']['data']['metadata']['product_name']
        
        for i in values['event']['data']['timeline']:
            if i['status'].lower()  == 'completed' or i['status'].lower() == 'overpaid' or i['status'].lower() == 'confirmed' or i['status'].lower() == 'paid':
                status = True

        if status:
            checkCode = CoinBaseProcess.objects.filter(code=code)
            if not checkCode:
                # New Payment Added
                if support_email == 'azizkrayyem7@gmail.com':
                    # Check about the product
                    # Check product type
                    product_info = Tool.objects.filter(id=int(product_id)).first()
                    if product_info:
                        # check if the product price is correct
                        # use Float To avoid number fraction loss
                        
                        if float(product_info.amount) == float(value) and payment_currency == 'USD':
                            # payment is correct, add the payment
                            CoinBaseProcess.objects.create(
                                code=code,
                                email=customer,
                                amount=value,
                                product_name=product_name,
                                product_id=product_id
                            )
                            # after customer purchase order send notification with tool data 
                            try:
                                user = User.objects.get(email=customer)
                                user_profile = Profile.objects.get(user=user)
                                user_profile.purchased_tools.add(product_info)
                                
                            except User.DoesNotExist:
                                error = _("User does not exist")
                            except user_profile.DoesNotExist:
                                error = _("User profile does not exist")
                            
                            # if you need to send email
                            
                        else:
                            error = _("price not correct")
                    else:
                        error = _("product does not exist")
            else:
                error = _("Duplicate ipn")
    return HttpResponse('ok')





def purchaesd_emails(request):
    # Get all users who have purchased any tool
    user_with_purchased_tools = User.objects.filter(profile__purchased_tools__isnull=False).distinct()
    
    # Get the emails of those users
    emails_of_users_with_purchased_tools = user_with_purchased_tools.values_list('email', flat=True)
    

theme/templates/tools/delete-product.html
{% extends 'base_theme.html' %}
{% load static %}
{% load i18n %}

{% block content %}
    <div class="container">
        <div class="tool-delete">
            <p class="dark:text-slate-50 text-slate-900">{% trans "Are u sure u want to delete" %} "{{ tool.tool_name }}"</p>
            <form method="POST">
                {% csrf_token %}
                <a class="btn btn-info" href="{{ request.META.HTTP_REFERER}}">{% trans "Cancel" %}</a>
                <input class="btn btn-danger" type="submit" name="{% trans "Delete" %}">
            </form>
        </div>
    </div>

{% endblock content %}

theme/templates/tools/product.html
{% extends 'base_theme.html' %}
{% load static %}
{% load i18n %}


{% block stylecss %}
    <link rel="stylesheet" href="{% static 'css/style-product.css' %}">
{% endblock stylecss %}

{% block content %}

{% include 'other/topnav.html' %}
{% include 'other/search.html' %}

<div class="parent-container">
    <div class="container">
        <div class="row">
            <!-- start product details-->
            <div class="col-md-8">
                <div class="product-details">
                    <div class="product-box shadow-5 border-3 dark:bg-slate-900 bg-slate-50">
                        <h1 class="product-title dark:text-gray-100 text-slate-900">{{ tool.tool_name }}</h1>
                        <div class="product-subtitle">
                            <span>
                                <span id="span1" class="dark:text-gray-100 text-slate-900">{% trans "Product sold" %}</span>
                                <span id="sapn2" class="">{{ tool.tool_sold }}</span>
                                <span id="sapn3" class="dark:text-gray-100 text-slate-900">{% trans "times" %}</span>
                            </span>
                        </div>
                        <div class="product-content">
                            <div class="row">
                                <div class="col-md-7">
                                    {% if tool.image %}
                                        <img src="{{ tool.image.url }}" alt="{{ tool.tool_name }}" class="product-image img-fluid rounded-4 shadow-2-strong hover-shadow lazyload">
                                    {% else %}
                                        <img class="card-img-top lazyload" src="{% static 'img/default-product-img.jpg' %}" alt="{{ tool.tool_name }}">
                                    {% endif %}
                                </div>
                                <div class="col-md-5 mt-md-0" style="padding: 0;">
                                    <div class="product-description dark:text-gray-100 text-slate-900">
                                        <h3 class="product-subtitle dark:text-gray-100 text-slate-900">{{ tool.tool_name }}</h3>
                                        <p>تفاصيل المنتج هنا</p>
                                        <p>تفاصيل أخرى</p>
                                        <p>...</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- end product details -->


            <!-- start product payment -->
            <div class="col-md-4">
                <div class="card-container">
                    <form action="{% url 'Coinbase_Payment' tool.id  %}"  method="post">
                        {% csrf_token %}
                    <div class="card dark:bg-slate-900 bg-slate-50"> 
                        <div class="card-body">
                            <h5 class="card-title dark:text-gray-100 text-slate-900">{% trans "Purchase" %}</h5>
                            <i class="fa-solid fa-xmark to-back dark:text-gray-100 text-slate-900"></i>
                        </div>
                        <div>
                            <div class="card-info">
                                <span class="card-text dark:text-gray-100 text-slate-900">{% trans "Subtotal" %}</span>
                                <span class="total-price dark:text-gray-100 text-slate-900">${{ tool.price }}</span>
                                <input type= "hidden" name="id" value="{{ tool.id }}" />
                            </div>
                            <div class="btn-purchase">
                                <button type="submit" class="btn btn-success ">
                                    {% trans "Pay-now" %} <i class="fa-solid fa-cart-shopping dark:text-gray-100 text-slate-900"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
                </div>
            </div>
        </div>
    </div>
    <!-- end product payment -->
</div>


{% endblock content %}

theme/templates/tools/products.html
{% extends 'base_theme.html' %}
{% load static %}
{% load i18n %}

{% block content %}

{% include 'other/topnav.html' %}
{% include 'other/search.html' %}


    <!-- start Card  -->
    <div class="container">
        <div class="card-box">
            {% for tool in tools %}
                {% if tool.is_visible %}
                    <div class="card">
                            <a href="{% url 'tool_detail' tool.slug %}">
                                <div class="bg-image hover-zoom">
                                    {% if tool.image %}
                                        <img class="card-img-top lazyload" data-src="{{ tool.image.url }}" alt="{{ tool.tool_name }}">
                                    {% else %}
                                        <img class="card-img-top lazyload" src="{% static 'img/default-product-img.jpg' %}" alt="{{ tool.tool_name }}">
                                    {% endif %}
                                </div>
                            </a>
                            <div class="card-body card-content dark:bg-slate-700 bg-slate-50">
                                <h5 class="card-title dark:text-gray-100 text-slate-900">{{ tool.tool_name }}</h5>
                                <div class="card-count-price">
                                    <p class="card-text dark:text-gray-100 text-slate-900">${{ tool.price }}</p>
                                    <span class="dark:text-gray-100 text-slate-900">
                                        {% trans "Stock" %}
                                        {% if tool.quantity > 10 %}
                                            <i class="fa-solid fa-infinity dark:text-green-500 text-green-600"></i>
                                        {% else %}
                                            <span class="dark:text-green-500 text-green-600">
                                                {{ tool.quantity }}
                                            </span>
                                        {% endif %}
                                    </span>
                                </div>
                                {% if request.user.is_superuser %}
                                    <div class="btn-admin">
                                        <a class="btn btn-info" href="{% url 'update_tool' tool.id %}">{% trans "update" %}</a>
                                        <a class="btn btn-danger" href="{% url 'delete_tool' tool.id %}">{% trans "delete" %}</a>
                                    </div>
                                {% endif %}
                            </div>
                    </div>
                {% endif %}
            {% endfor %}
            <!-- Add more cards here -->
        </div>
    </div>
    <!-- end Card  -->


{% endblock content %}

theme/templates/tools/search_results.html
{% extends 'base_theme.html' %}
{% load static %}
{% load i18n %}


{% block content %}


{% include 'other/topnav.html' %}
{% include 'other/search.html' %}


<!-- start Card  -->
<div class="container">
    {% if tools %}
    <div class="card-box">
        {% for tool in tools %}
            {% if tool.is_visible %}
                <div class="card">
                        <a href="{% url 'tool_detail' tool.slug %}">
                            <div class="bg-image hover-zoom">
                                {% if tool.image %}
                                    <img class="card-img-top lazyload" data-src="{{ tool.image.url }}" alt="{{ tool.tool_name }}">
                                {% else %}
                                    <img class="card-img-top lazyload" src="{% static 'img/default-product-img.jpg' %}" alt="{{ tool.tool_name }}">
                                {% endif %}
                            </div>
                        </a>
                        <div class="card-body card-content dark:bg-slate-700 bg-gray-100">
                            <h5 class="card-title dark:text-gray-100 text-slate-900">{{ tool.tool_name }}</h5>
                            <div class="card-count-price">
                                <p class="card-text dark:text-gray-100 text-slate-900">${{ tool.price }}</p>
                                <span class="dark:text-gray-100 text-slate-900">
                                    {% trans "Stock" %}
                                    {% if tool.quantity > 10 %}
                                        <i class="fa-solid fa-infinity dark:text-green-500 text-green-600"></i>
                                    {% else %}
                                        <span class="dark:text-green-500 text-green-600">
                                            {{ tool.quantity }}
                                        </span>
                                    {% endif %}
                                </span>
                            </div>
                            {% if request.user.is_superuser %}
                                <div class="btn-admin">
                                    <a class="btn btn-info" href="{% url 'update_tool' tool.id %}">{% trans "update" %}</a>
                                    <a class="btn btn-danger" href="{% url 'delete_tool' tool.id %}">{% trans "delete" %}</a>
                                </div>
                            {% endif %}
                        </div>
                </div>
            {% endif %}
        {% endfor %}
        <!-- Add more cards here -->
    </div>
    {% else %}
        <div class="not-found">
            <p class="dark:text-slate-50 text-slate-900">{% trans "No results found." %}</p>
        </div>
    {% endif %}
</div>
<!-- end Card  -->

{% endblock content %}

theme/templates/tools/tool_form.html
{% extends 'base_theme.html' %}
{% load static %}
{% load i18n %}

{% block content %}
    <form class="form-box box-login-register-form dark:bg-slate-800 bg-slate-50 " method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="container">

            <div class="form-outline">
                <input type="text" id="id_name" class="form-control text-slate-900 dark:text-gray-50 " name="tool_name" value="{% if form.tool_name.value %}{{ form.tool_name.value }}{% endif %}" required/>
                <label class="form-label dark:text-gray-50" for="id_name">{% trans "Name" %}</label>
            </div>

            <div class="">
                <select class="form-select dark:text-gray-50 dark:bg-slate-800 bg-slate-50" aria-label="Default select example" name="type_of_tool">
                    {% for type_tool in type_tools %}
                        <option value="{{ type_tool.id }}">{{ type_tool.name }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="form-outline">
                <input type="number" id="id_price" class="form-control text-slate-900 dark:text-gray-50" name="price" value="{% if form.price.value %}{{ form.price.value }}{% endif %}" required/>
                <label class="form-label dark:text-gray-50" for="id_price">{% trans "Price" %}</label>
            </div>
            
            <div class="form-outline">
                <input type="text" id="id_token" class="form-control text-slate-900 dark:text-gray-50" name="token" value="{% if form.token.value %}{{ form.token.value }}{% endif %}" required/>
                <label class="form-label dark:text-gray-50" for="id_token">{% trans "Token" %}</label>
            </div>
            
            <div class="form-outline">
                <input type="number" id="id_quantity" class="form-control text-slate-900 dark:text-gray-50" name="quantity" value="{% if form.quantity.value %}{{ form.quantity.value }}{% endif %}" required/>
                <label class="form-label dark:text-gray-50" for="id_quantity">{% trans "Quantity" %}</label>
            </div> 

            <div class="form-upload">
                <label class="form-label dark:text-gray-50" for="id_image">{% trans "Image" %}:</label>
                <input type="file" class="form-control text-slate-900 dark:text-gray-900" id="id_image" name="image" value="{% if form.image.value %}{{ form.image.value }}{% endif %}" required/>
            </div>

            <div class="form-upload">
                <label class="form-label dark:text-gray-50" for="id_upload_tool">{% trans "Upload tool" %}:</label>
                <input type="file" class="form-control text-slate-900 dark:text-gray-900" id="id_upload_tool" name="upload_tool" value="{% if form.upload_tool.value %}{{ form.upload_tool.value }}{% endif %}" required/>
            </div> 

            <!-- btn -->
            <div class="buttons">
                <input type="submit" class="btn btn-success" name="{% trans "Submit" %}"/>
                <input type="reset" class="btn btn-danger" value="{% trans "Reset" %}">
            </div>
            
        </div>
    </form>
{% endblock content %}